#!/bin/python3

height = float(input("enter your height in m: "))
weight = float(input("enter your weight in kg: "))

bmi = weight / height ** 2
result = round(bmi)

if result <= 18.5:
  print(f'Your bmi is {result} and you are underweight.')
elif result <= 25:
  print(f'Your bmi is {result}, you are normal weight.')
elif result <= 30:
  print(f'Your bmi is {result}, you are slightly overweight.')
elif result <= 35:
    print(f'Your bmi is {result} and you are obese.')
else:
    print(f'Your bmi is {result} and you are clinically obese.')
