#!/bin/python3

student_scores = {
  "Harry": 81,
  "Ron": 78,
  "Hermione": 99, 
  "Draco": 74,
  "Neville": 62,
}
student_grades = {}
for student in student_scores:
  score = student_scores[student]
  if score > 90:
    student_grades[student] = "Outstanding " + str(score)
  elif score > 80:
    student_grades[student] = "Exceeds Expectations "+ str(score)
  elif score >= 70:
    student_grades[student] = "Acceptable " + str(score)
  else:
    student_grades[student] = "Fail "+ str(score)
    

print(student_grades)
