#!/bin/python3

import random

rock = '''
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
'''

paper = '''
    _______
---'   ____)____
          ______)
          _______)
         _______)
---.__________)
'''

scissors = '''
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
'''
game_images = [rock, paper, scissors]

user_choice = int(input("What do you choose? Type 0 for Rock, 1 for Paper or 2 for Scissors.\n"))
print(game_images[user_choice])

computer_choice = random.randint(0, 2)
print("Computer chose:")
print(game_images[computer_choice])

if user_choice >= 3 or user_choice < 0: 
  print("You typed an invalid number, you lose!") 
elif user_choice == 0 and computer_choice == 2:
  print("You win!")
elif computer_choice == 0 and user_choice == 2:
  print("You lose")
elif computer_choice > user_choice:
  print("You lose")
elif user_choice > computer_choice:
  print("You win!")
elif computer_choice == user_choice:
  print("It's a draw")





#alternative
# scissors = 0
# paper = 1
# rock = 2
# input1 = int(input("Choose scissor=0 paper=1 rock=2\n"))
# print("You choosed:\n")
# print( scissorsim if input1 == 0 else paperim if input1 == 1 else rockim )

# input2 = random.randint(0,2)
# print("Computer Choosed:")
# print( scissorsim if input2 == 0 else paperim if input2 == 1 else rockim )

# if input1 == input2 :
#     print("it's a tie\n")
# elif input1 > 2:
#     print("invalid number you lose")
# else:
#     if input1 == scissors and input2 == paper or input1 == rock and input2 == scissors or input1 == paper and input2 == rock :
#         print("You Win\n")
#     else:
#         print("You Lose\n")
