#!/bin/python

import random

rock = '''
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
'''

paper = '''
    _______
---'   ____)____
          ______)
          _______)
         _______)
---.__________)
'''

scissors = '''
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
'''
# User choice
user = int(input('What do you choose? Type 0 for Rock, 1 for Paper or 2 for Scissors.\n'))

# computer random choice
computer = random.randint(0,2)

#Compare to see who win
if user == 0 and computer == 0:
  print(f'{rock},{rock}\n Tie Game')
elif user == 0 and computer == 1:
  print(rock)
  print(paper)
  print('Paper beat rock computer win')
elif user == 0 and computer == 2:
  print(rock)
  print(scissors)
  print('User win rock beat scissors')
elif user == 1 and computer == 0:
    print(paper)
    print(rock)
    print('User beat computer paper wins over rock')
elif user == 1 and computer == 1:
    print(paper)
    print(paper)
    print('Tie Game, Play again')
elif user == 1 and computer == 2:
    print(paper)
    print(scissors)
    print('Computer win scissors beat paper')
elif user == 2 and computer == 0:
    print(scissors)
    print(rock)
    print('Computer win rock wins over scissors')
elif user == 2 and computer == 1:
    print(scissors)
    print(paper)
    print('User win scissors beat paper')
elif user == 2 and computer == 2:
    print(scissors)
    print(scissors)
    print('Tie game, Play again!')
